language: node_js
node_js:
  - '8'
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - npm install
install:
  - npm install
script:
  - npm test
  - npm run coveralls